CREATE TABLE blog_user(

	`uid` INT AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(20) NOT NULL COMMENT '用户名',
	`emil` VARCHAR(50) NOT NULL COMMENT '邮箱',
	`password` VARCHAR(50) NOT NULL COMMENT '密码'

)CHARSET utf8 COMMENT '博客用户表1';


20191105 CREATE BY TCH